export function isEmptyArray(arr: any): boolean;
export function isEmptyValue(value: any): boolean;
export function isDefined(val: any): boolean;
export function isObject(val: any): boolean;
export function isFunction(val: any): boolean;
export function isBoolean(val: any): boolean;
export function isNumber(val: any): boolean;
export function isTrue(val: any): any;
export function isFalse(val: any): boolean;
export function getValByUnit(width: any): any;
export function getParentCompByName(context: any, name: any): any;
export function getChildCompsByName(context: any, name: any): any[];
export function scrollTo(el: any, option: any): void;
import debounce from './debounce.js';
import cloneDeep from './cloneDeep.js';
export { debounce, cloneDeep };
