declare namespace _default {
    export { install };
    export { version };
    export { VeCheckbox };
    export { VeCheckboxGroup };
    export { VeContextmenu };
    export { VeDropdown };
    export { VeIcon };
    export { VeLoading };
    export { VeLocale };
    export { VePagination };
    export { VeRadio };
    export { VeSelect };
    export { FanTable };
}
export default _default;
export function install(app: any): void;
import { version } from '../package.json';
import VeCheckbox from './ve-checkbox/ve-checkbox.js';
import VeCheckboxGroup from './ve-checkbox-group/ve-checkbox-group.js';
import VeContextmenu from './ve-contextmenu/ve-contextmenu.js';
import VeDropdown from './ve-dropdown/ve-dropdown.js';
import VeIcon from './ve-icon/ve-icon.js';
import VeLoading from './ve-loading/ve-loading.js';
import VeLocale from './ve-locale/ve-locale.js';
import VePagination from './ve-pagination/ve-pagination.js';
import VeRadio from './ve-radio/ve-radio.js';
import VeSelect from './ve-select/ve-select.js';
import FanTable from './fan-table/fan-table.js';
export { version, VeCheckbox, VeCheckboxGroup, VeContextmenu, VeDropdown, VeIcon, VeLoading, VeLocale, VePagination, VeRadio, VeSelect, FanTable };
