// global events
export default {
// EMIT_EVENTS.SORT_CHANGE
// EMIT_EVENTS.CHECKBOX_SELECTED_ALL_CHANGE
// EMIT_EVENTS.CHECKBOX_SELECTED_ALL_INFO
// EMIT_EVENTS.HEADER_ROW_HEIGHT_CHANGE
// EMIT_EVENTS.BODY_ROW_HEIGHT_CHANGE
// EMIT_EVENTS.FOOTER_ROW_HEIGHT_CHANGE
// EMIT_EVENTS.BODY_CELL_CLICK
// EMIT_EVENTS.BODY_CELL_MOUSEOVER
// EMIT_EVENTS.BODY_CELL_MOUSEDOWN
// EMIT_EVENTS.BODY_CELL_MOUSEMOVE
// EMIT_EVENTS.BODY_CELL_MOUSEUP
// EMIT_EVENTS.SELECTION_CORNER_MOUSEDOWN
// EMIT_EVENTS.SELECTION_CORNER_MOUSEUP
// EMIT_EVENTS.AUTOFILLING_DIRECTION_CHANGE
// EMIT_EVENTS.BODY_CELL_CONTEXTMENU
// EMIT_EVENTS.BODY_CELL_DOUBLE_CLICK
// EMIT_EVENTS.HEADER_CELL_CLICK
// EMIT_EVENTS.HEADER_CELL_CONTEXTMENU
// EMIT_EVENTS.HEADER_CELL_MOUSEDOWN
// EMIT_EVENTS.HEADER_CELL_MOUSEOVER
// EMIT_EVENTS.HEADER_CELL_MOUSEMOVE
// EMIT_EVENTS.HEADER_CELL_MOUSELEAVE
// EMIT_EVENTS.CHECKBOX_SELECTED_ROW_CHANGE
// EMIT_EVENTS.CHECKBOX_SELECTED_ALL_CHANGE
// EMIT_EVENTS.RADIO_SELECTED_ROW_CHANGE
// EMIT_EVENTS.BODY_ROW_CLICK
// EMIT_EVENTS.CHECKBOX_SELECTED_ALL_INFO
// EMIT_EVENTS.SORT_CHANGE
}
