// global events
export const GLOBAL_EVENT = {
  SORT_CHANGE: 'sort-change',
  SORT_CHANGE_AFTER: 'sort-change-after',
  CHECKBOX_SELECTED_ALL_CHANGE_BODY: 'checkbox-selected-all-change-body',
  CHECKBOX_SELECTED_ALL_CHANGE_TABLE: 'checkbox-selected-all-change-table',
  CHECKBOX_SELECTED_ALL_INFO: 'checkbox-selected-all-info',
  CHECKBOX_SELECTED_ALL_INFO_CHECKBOX: 'checkbox-selected-all-info-checkbox',
  HEADER_ROW_HEIGHT_CHANGE: 'header-row-height-change',
  BODY_ROW_HEIGHT_CHANGE: 'body-row-height-change',
  FOOTER_ROW_HEIGHT_CHANGE: 'footer-row-height-change',
  BODY_CELL_CLICK: 'body-cell-click',
  BODY_CELL_MOUSEOVER: 'body-cell-mouseover',
  BODY_CELL_MOUSEDOWN: 'body-cell-mousedown',
  BODY_CELL_MOUSEMOVE: 'body-cell-mousemove',
  BODY_CELL_MOUSEUP: 'body-cell-mouseup',
  SELECTION_CORNER_MOUSEDOWN: 'selection-corner-mousedown',
  SELECTION_CORNER_MOUSEUP: 'selection-corner-mouseup',
  AUTOFILLING_DIRECTION_CHANGE: 'autofilling-direction-change',
  BODY_CELL_CONTEXTMENU: 'body-cell-contextmenu',
  BODY_CELL_DOUBLE_CLICK: 'body-cell-double-click',
  HEADER_CELL_CLICK: 'header-cell-click',
  HEADER_CELL_CONTEXTMENU: 'header-cell-contextmenu',
  HEADER_CELL_MOUSEDOWN: 'header-cell-mousedown',
  HEADER_CELL_MOUSEOVER: 'header-cell-mouseover',
  HEADER_CELL_MOUSEMOVE: 'header-cell-mousemove',
  HEADER_CELL_MOUSELEAVE: 'header-cell-mouseleave',
  CHECKBOX_SELECTED_ROW_CHANGE: 'checkbox-selected-row-change',
  RADIO_SELECTED_ROW_CHANGE: 'radio-selected-row-change',
  BODY_ROW_CLICK: 'body-row-click',
}
